import { useEffect, useState } from 'react';
import { FileCheck2, RefreshCw, Send, ShieldCheck } from 'lucide-react';
import { DashboardLayout } from '@/components/DashboardLayout';
import { Card, LoadingPage, Pagination, StatCard } from '@/components/ui';
import { adminNav } from '@/components/dashboardNav';
import { supabase } from '@/lib/supabase';
import { useToast } from '@/context/hooks';

type Settings = { enabled:boolean; environment:'sandbox'|'production'; taxpayer_pin:string|null; branch_id:string; default_item_code:string|null; default_item_classification_code:string|null; default_item_name:string; default_tax_type_code:string|null; default_tax_rate:number|null; registration_name:string|null; registration_id:string|null };
type Invoice = { id:string; period:string; amount:number; balance:number; status:string; due_date:string; kra_submission_status:string; kra_invoice_number:number|null; kra_result_message:string|null; profiles?:{full_name:string|null}|null; properties?:{name:string}|null; property_units?:{unit_number:string}|null };

export function AdminKra() {
  const { toast } = useToast(); const [settings,setSettings]=useState<Settings>({enabled:false,environment:'sandbox',taxpayer_pin:null,branch_id:'00',default_item_code:null,default_item_classification_code:null,default_item_name:'Property management / rental service',default_tax_type_code:null,default_tax_rate:null,registration_name:null,registration_id:null});
  const [invoices,setInvoices]=useState<Invoice[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [page,setPage]=useState(1); const [total,setTotal]=useState(0); const [submitting,setSubmitting]=useState<string|null>(null);
  const pageSize=20;
  const load=async()=>{setLoading(true);const [{data:s,error:se},{data, count,error}]=await Promise.all([supabase.rpc('get_admin_kra_etims_settings'),supabase.from('rent_invoices').select('id,period,amount,balance,status,due_date,kra_submission_status,kra_invoice_number,kra_result_message,profiles:tenant_id(full_name),properties:property_id(name),property_units:unit_id(unit_number)',{count:'exact'}).order('created_at',{ascending:false}).range((page-1)*pageSize,page*pageSize-1)]);if(se)toast(se.message,'error');if(error)toast(error.message,'error');if(s)setSettings(s as Settings);setInvoices((data as unknown as Invoice[])||[]);setTotal(count||0);setLoading(false)};
  useEffect(()=>{void load()},[page]);
  const save=async()=>{setSaving(true);const payload={...settings,branch_id:String(settings.branch_id||'00').trim()||'00',default_tax_rate:settings.default_tax_rate===null?null:Number(settings.default_tax_rate)};const {data,error}=await supabase.rpc('admin_save_kra_etims_settings',{p_settings:payload});setSaving(false);if(error){toast(error.message,'error');return;}if(data&&typeof data==='object')setSettings((prev)=>({...prev,...(data as Partial<Settings>)}));toast('KRA eTIMS configuration saved.','success')};
  const kraConfigReady=Boolean(settings.enabled&&settings.taxpayer_pin&&settings.default_item_code&&settings.default_item_classification_code&&settings.default_tax_type_code&&settings.default_tax_rate!==null);
  const submit=async(id:string)=>{if(!kraConfigReady){toast('KRA eTIMS is not configured yet. Keep this module dormant until KRA credentials and item/tax configuration are available.','error');return;}setSubmitting(id);const {data,error}=await supabase.functions.invoke('kra-etims-invoice',{body:{invoice_id:id}});setSubmitting(null);if(error)toast(error.message,'error');else if(data?.error)toast(data.error,'error');else {toast('Invoice submitted to KRA eTIMS successfully.','success');void load()}};
  if(loading)return <DashboardLayout navItems={adminNav} title="KRA eTIMS"><LoadingPage/></DashboardLayout>;
  const submitted=invoices.filter(x=>x.kra_submission_status==='submitted').length, pending=invoices.filter(x=>x.kra_submission_status!=='submitted').length;
  return <DashboardLayout navItems={adminNav} title="KRA eTIMS"><div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-700">Tax compliance</p><h1 className="mt-1 text-2xl font-bold text-ink-950">KRA eTIMS control centre</h1><p className="mt-1 text-sm text-ink-500">Configure OSCU/VSCU invoicing and submit rent invoices to KRA with a complete audit trail.</p></div><button onClick={()=>void load()} className="btn-secondary"><RefreshCw className="h-4 w-4"/> Refresh</button></div>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><StatCard label="eTIMS status" value={kraConfigReady?'Ready':'Not configured'} icon={<ShieldCheck className="h-5 w-5"/>} accent={settings.enabled?'brand':'accent'}/><StatCard label="Submitted · page" value={submitted} icon={<FileCheck2 className="h-5 w-5"/>} accent="blue"/><StatCard label="Awaiting submission · page" value={pending} icon={<Send className="h-5 w-5"/>}/></div>
    <Card><div className="border-b border-ink-100 p-5"><h2 className="font-bold text-ink-900">OSCU configuration</h2><p className="mt-1 text-xs text-ink-500">Secrets such as the KRA communication key remain server-side in Supabase.</p></div><div className="grid grid-cols-1 gap-4 p-5 md:grid-cols-2 lg:grid-cols-3">
      <label className="label">Environment<select className="input mt-1" value={settings.environment} onChange={e=>setSettings({...settings,environment:e.target.value as Settings['environment']})}><option value="sandbox">Sandbox</option><option value="production">Production</option></select></label>
      <label className="label">Enabled<select className="input mt-1" value={settings.enabled?'yes':'no'} onChange={e=>setSettings({...settings,enabled:e.target.value==='yes'})}><option value="no">No</option><option value="yes">Yes</option></select></label>
      <label className="label">KRA PIN<input className="input mt-1" value={settings.taxpayer_pin||''} onChange={e=>setSettings({...settings,taxpayer_pin:e.target.value||null})}/></label>
      <label className="label">Branch ID<input className="input mt-1" value={settings.branch_id} onChange={e=>setSettings({...settings,branch_id:e.target.value})}/></label>
      <label className="label">KRA item code<input className="input mt-1" value={settings.default_item_code||''} onChange={e=>setSettings({...settings,default_item_code:e.target.value||null})}/></label>
      <label className="label">Item classification code<input className="input mt-1" value={settings.default_item_classification_code||''} onChange={e=>setSettings({...settings,default_item_classification_code:e.target.value||null})}/></label>
      <label className="label md:col-span-2">Invoice item name<input className="input mt-1" value={settings.default_item_name} onChange={e=>setSettings({...settings,default_item_name:e.target.value})}/></label>
      <label className="label">Tax type code<input className="input mt-1" placeholder="Set from KRA/accountant" value={settings.default_tax_type_code||''} onChange={e=>setSettings({...settings,default_tax_type_code:e.target.value||null})}/></label>
      <label className="label">Tax rate %<input type="number" step="0.01" className="input mt-1" value={settings.default_tax_rate??''} onChange={e=>setSettings({...settings,default_tax_rate:e.target.value===''?null:Number(e.target.value)})}/></label>
      <label className="label">Registration ID<input className="input mt-1" value={settings.registration_id||''} onChange={e=>setSettings({...settings,registration_id:e.target.value||null})}/></label>
      <label className="label">Registration name<input className="input mt-1" value={settings.registration_name||''} onChange={e=>setSettings({...settings,registration_name:e.target.value||null})}/></label>
    </div><div className="flex justify-end border-t border-ink-100 p-5"><button disabled={saving} onClick={()=>void save()} className="btn-primary">{saving?'Saving…':'Save configuration'}</button></div></Card>
    <Card><div className="border-b border-ink-100 p-5"><h2 className="font-bold text-ink-900">Rent invoice eTIMS queue</h2><p className="mt-1 text-xs text-ink-500">KRA eTIMS remains dormant until the required KRA credentials and correct item/tax configuration are available.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-ink-50 text-left text-xs uppercase tracking-wider text-ink-500"><tr><th className="px-5 py-3">Tenant / property</th><th className="px-5 py-3">Period</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">eTIMS</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-ink-100">{invoices.map(i=><tr key={i.id}><td className="px-5 py-4"><p className="font-semibold text-ink-800">{i.profiles?.full_name||'Tenant'}</p><p className="text-xs text-ink-400">{i.properties?.name||'Property'} · Unit {i.property_units?.unit_number||'—'}</p></td><td className="px-5 py-4">{i.period}</td><td className="px-5 py-4 font-semibold">KES {Number(i.amount).toLocaleString()}</td><td className="px-5 py-4"><span className="badge bg-ink-100 text-ink-600">{i.kra_submission_status}</span>{i.kra_invoice_number&&<p className="mt-1 text-[11px] text-brand-700">KRA #{i.kra_invoice_number}</p>}{i.kra_result_message&&i.kra_submission_status==='failed'&&<p className="mt-1 max-w-xs text-[11px] text-red-600">{i.kra_result_message}</p>}</td><td className="px-5 py-4 text-right">{i.kra_submission_status!=='submitted'&&<button disabled={!kraConfigReady||submitting===i.id} onClick={()=>void submit(i.id)} className="btn-secondary"><Send className="h-4 w-4"/>{submitting===i.id?'Submitting…':'Submit to KRA'}</button>}</td></tr>)}</tbody></table></div><Pagination page={page} totalPages={Math.max(1,Math.ceil(total/pageSize))} totalItems={total} pageSize={pageSize} onPageChange={setPage}/></Card>
  </div></DashboardLayout>;
}
