import { useEffect, useState } from 'react';
import { BadgeDollarSign, FileCheck2, HandCoins, LandPlot, Plus, RefreshCw, Search, ShieldCheck, TrendingUp } from 'lucide-react';
import { DashboardLayout } from '@/components/DashboardLayout';
import { adminNav, ownerNav } from '@/components/dashboardNav';
import { Badge, Card, EmptyState, LoadingPage, Pagination, StatCard } from '@/components/ui';
import { Modal } from '@/components/Modal';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/context/hooks';
import { useToast } from '@/context/hooks';
import { formatKES, titleCase } from '@/lib/constants';
import { DonutChart } from '@/components/AnalyticsCharts';

type SaleRow = { id:string; property_id:string; listing_code:string|null; sale_type:string; listing_status:string; asking_price:number; negotiable:boolean; reservation_amount:number; title_verified:boolean; survey_verified:boolean; marketing_summary:string|null; properties?: { name:string; town:string; county:string }|{name:string;town:string;county:string}[]|null };
type OfferRow = { id:string; sale_listing_id:string; buyer_name:string|null; buyer_phone:string|null; offer_amount:number; offer_status:string; created_at:string; sale_listings?: { listing_code:string|null }|{listing_code:string|null}[]|null };

function SalesOperations({ ownerOnly=false }:{ownerOnly?:boolean}) {
  const { profile } = useAuth(); const { toast } = useToast();
  const [rows,setRows]=useState<SaleRow[]>([]); const [offers,setOffers]=useState<OfferRow[]>([]); const [loading,setLoading]=useState(true); const [page,setPage]=useState(1); const [total,setTotal]=useState(0); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [type,setType]=useState('all'); const [show,setShow]=useState(false); const [saving,setSaving]=useState(false); const [properties,setProperties]=useState<Array<{id:string;name:string}>>([]); const [form,setForm]=useState({property_id:'',sale_type:'land',asking_price:'',reservation_amount:'',negotiable:true,marketing_summary:''});
  const load=async()=>{setLoading(true); const from=(page-1)*20,to=from+19; let q=supabase.from('sale_listings').select('id,property_id,listing_code,sale_type,listing_status,asking_price,negotiable,reservation_amount,title_verified,survey_verified,marketing_summary,properties(name,town,county)',{count:'exact'}); if(ownerOnly&&profile?.id){ const owned=(await supabase.from('properties').select('id').eq('owner_id',profile.id)); const ids=(owned.data||[]).map(x=>x.id); q=ids.length?q.in('property_id',ids):q.eq('property_id','00000000-0000-0000-0000-000000000000'); } if(status!=='all')q=q.eq('listing_status',status); if(type!=='all')q=q.eq('sale_type',type); if(query.trim()){const s=query.trim().replace(/[%_]/g,''); q=q.or(`listing_code.ilike.%${s}%,marketing_summary.ilike.%${s}%`);} const {data,count,error}=await q.order('created_at',{ascending:false}).range(from,to); if(error)toast(`Could not load sales: ${error.message}`,'error'); setRows((data as SaleRow[])||[]); setTotal(count||0); const {data:of}=await supabase.from('sale_offers').select('id,sale_listing_id,buyer_name,buyer_phone,offer_amount,offer_status,created_at,sale_listings(listing_code)').order('created_at',{ascending:false}).limit(8); setOffers((of as OfferRow[])||[]); setLoading(false);};
  useEffect(()=>{setPage(1)},[query,status,type]); useEffect(()=>{void load()},[page,query,status,type,ownerOnly,profile?.id]);
  useEffect(()=>{(async()=>{let q=supabase.from('properties').select('id,name').order('name'); if(ownerOnly&&profile?.id)q=q.eq('owner_id',profile.id); const {data}=await q.limit(200);setProperties((data||[]) as Array<{id:string;name:string}>);})()},[ownerOnly,profile?.id]);
  const create=async()=>{if(!form.property_id||!form.asking_price){toast('Select an asset and enter the asking price','error');return;} setSaving(true); const {error}=await supabase.from('sale_listings').insert({property_id:form.property_id,sale_type:form.sale_type,asking_price:Number(form.asking_price),reservation_amount:Number(form.reservation_amount||0),negotiable:form.negotiable,marketing_summary:form.marketing_summary||null,created_by:profile?.id,listing_status:'draft'});setSaving(false);if(error){toast(`Could not create sale listing: ${error.message}`,'error');return;}setShow(false);setForm({property_id:'',sale_type:'land',asking_price:'',reservation_amount:'',negotiable:true,marketing_summary:''});toast('Sale listing created','success');void load();};
  const setListingStatus=async(id:string,next:string)=>{const {error}=await supabase.from('sale_listings').update({listing_status:next}).eq('id',id);if(error)toast(`Could not update listing: ${error.message}`,'error');else{toast(`Listing marked ${next}`,'success');void load();}};
  if(loading&&!rows.length)return <DashboardLayout navItems={ownerOnly?ownerNav:adminNav} title="Sales & Disposals"><LoadingPage/></DashboardLayout>;
  const props=(r:SaleRow)=>Array.isArray(r.properties)?r.properties[0]:r.properties;
  return <DashboardLayout navItems={ownerOnly?ownerNav:adminNav} title="Sales & Disposals">
    <div className="mb-7 rounded-2xl brand-gradient p-6 text-white shadow-soft-lg"><p className="text-sm font-semibold text-white/90">Phase 9 · Sales & disposals</p><h2 className="mt-1 text-2xl font-bold">Land & property sales command centre</h2><p className="mt-2 max-w-3xl text-sm text-white/90">List land, plots, completed properties and development opportunities, manage offers and move accepted deals through a controlled completion pipeline.</p></div>
    <div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard label="Active listings" value={rows.filter(r=>r.listing_status==='active').length} icon={<TrendingUp className="h-5 w-5"/>} accent="blue"/><StatCard label="Reserved" value={rows.filter(r=>r.listing_status==='reserved').length} icon={<ShieldCheck className="h-5 w-5"/>}/><StatCard label="Pending offers" value={offers.filter(o=>['submitted','under_review'].includes(o.offer_status)).length} icon={<HandCoins className="h-5 w-5"/>} accent="accent"/><StatCard label="Pipeline value" value={formatKES(rows.reduce((s,r)=>s+(Number(r.asking_price)||0),0))} icon={<BadgeDollarSign className="h-5 w-5"/>} accent="red"/></div>
    <div className="mb-6 grid grid-cols-1 gap-6 xl:grid-cols-2"><DonutChart segments={Object.entries(rows.reduce((acc,r)=>{const k=titleCase(r.listing_status);acc[k]=(acc[k]||0)+1;return acc;},{} as Record<string,number>)).map(([label,value])=>({label,value}))} centerLabel="Listings" centerValue={String(rows.length)} /><Card className="p-5"><p className="chart-kicker">Commercial pipeline</p><p className="chart-caption">Offer momentum</p><div className="mt-5 grid grid-cols-2 gap-3">{[['Active',rows.filter(r=>r.listing_status==='active').length],['Reserved',rows.filter(r=>r.listing_status==='reserved').length],['Sold',rows.filter(r=>r.listing_status==='sold').length],['Offers',offers.length]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-ink-50 p-4"><p className="text-2xl font-bold text-brand-700">{value}</p><p className="mt-1 text-xs text-ink-500">{label}</p></div>)}</div></Card></div>
    <Card className="mb-5 p-4"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-400"/><input className="input pl-10" placeholder="Search listing code or marketing notes…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="input lg:w-48" value={type} onChange={e=>setType(e.target.value)}><option value="all">All sale types</option><option value="land">Land / plot</option><option value="property">Built property</option><option value="development">Development</option></select><select className="input lg:w-48" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{['draft','active','reserved','sold','withdrawn'].map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</select><button className="btn-secondary" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</button><button className="btn-primary" onClick={()=>setShow(true)}><Plus className="h-4 w-4"/>New sale listing</button></div></Card>
    {rows.length?<Card className="overflow-hidden"><div className="border-b border-ink-100 px-5 py-4"><h3 className="font-semibold text-ink-900">Sale listing register</h3><p className="text-xs text-ink-500">{total} listing{total===1?'':'s'} · server paginated</p></div><div className="overflow-x-auto"><table className="premium-table w-full min-w-[1050px] text-sm"><thead><tr><th>Listing</th><th>Asset</th><th>Price</th><th>Due diligence</th><th>Status</th><th>Workflow</th></tr></thead><tbody>{rows.map(r=>{const p=props(r);return <tr key={r.id}><td><p className="font-semibold text-ink-900">{r.listing_code||'SALE'}</p><p className="text-xs text-ink-400">{titleCase(r.sale_type)}</p></td><td><p className="font-medium">{p?.name||'Asset'}</p><p className="text-xs text-ink-400">{p?.town||''}{p?.county?`, ${p.county}`:''}</p></td><td><p className="font-semibold">{formatKES(Number(r.asking_price)||0)}</p>{r.negotiable&&<span className="text-xs text-brand-700">Negotiable</span>}</td><td><div className="flex gap-1.5">{r.title_verified?<Badge><FileCheck2 className="mr-1 h-3 w-3"/>Title verified</Badge>:<Badge status="pending">Title pending</Badge>}{r.survey_verified&&<Badge>Survey</Badge>}</div></td><td><Badge status={r.listing_status}>{titleCase(r.listing_status)}</Badge></td><td><div className="flex gap-2">{r.listing_status==='draft'&&<button className="btn-secondary text-xs" onClick={()=>void setListingStatus(r.id,'active')}>Publish</button>}{r.listing_status==='active'&&<button className="btn-secondary text-xs" onClick={()=>void setListingStatus(r.id,'reserved')}>Reserve</button>}{r.listing_status==='reserved'&&<button className="btn-primary text-xs" onClick={()=>void setListingStatus(r.id,'sold')}>Complete sale</button>}</div></td></tr>})}</tbody></table></div></Card>:<Card><EmptyState icon={<LandPlot className="h-8 w-8"/>} title="No sale listings yet" description="Create your first land, property or development sale listing to start the sales pipeline." action={<button className="btn-primary" onClick={()=>setShow(true)}><Plus className="h-4 w-4"/>Create listing</button>}/></Card>}
    <Pagination page={page} totalPages={Math.max(1,Math.ceil(total/20))} totalItems={total} pageSize={20} onPageChange={setPage}/>
    <Card className="mt-6"><div className="border-b border-ink-100 px-5 py-4"><h3 className="font-semibold">Recent offers</h3><p className="text-xs text-ink-500">Offer activity requiring commercial follow-up</p></div><div className="divide-y divide-ink-100">{offers.map(o=>{const sl=Array.isArray(o.sale_listings)?o.sale_listings[0]:o.sale_listings;return <div key={o.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{o.buyer_name||'Prospective buyer'} · {sl?.listing_code||'Listing'}</p><p className="text-xs text-ink-500">{o.buyer_phone||'No phone'} · {new Date(o.created_at).toLocaleDateString()}</p></div><div className="text-right"><p className="font-bold">{formatKES(Number(o.offer_amount)||0)}</p><Badge status={o.offer_status}>{titleCase(o.offer_status)}</Badge></div></div>})}{!offers.length&&<p className="p-5 text-sm text-ink-500">No offers recorded yet.</p>}</div></Card>
    <Modal open={show} onClose={()=>setShow(false)} title="Create sale listing"><div className="space-y-4"><select className="input" value={form.property_id} onChange={e=>setForm({...form,property_id:e.target.value})}><option value="">Select property / land asset</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="input" value={form.sale_type} onChange={e=>setForm({...form,sale_type:e.target.value})}><option value="land">Land / plot</option><option value="property">Built property</option><option value="development">Development project</option></select><div className="grid grid-cols-2 gap-3"><input className="input" type="number" min="0" placeholder="Asking price (KES)" value={form.asking_price} onChange={e=>setForm({...form,asking_price:e.target.value})}/><input className="input" type="number" min="0" placeholder="Reservation amount" value={form.reservation_amount} onChange={e=>setForm({...form,reservation_amount:e.target.value})}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.negotiable} onChange={e=>setForm({...form,negotiable:e.target.checked})}/> Price is negotiable</label><textarea className="input min-h-28" placeholder="Marketing summary / key selling points" value={form.marketing_summary} onChange={e=>setForm({...form,marketing_summary:e.target.value})}/><div className="flex justify-end gap-3"><button className="btn-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="btn-primary" disabled={saving} onClick={()=>void create()}>{saving?'Creating…':'Create listing'}</button></div></div></Modal>
  </DashboardLayout>
}
export function AdminSales(){return <SalesOperations/>} export function OwnerSales(){return <SalesOperations ownerOnly/>}
