import { ADMIN_PERMISSION } from '@/lib/staffAccess';
import { Home, LayoutDashboard, Building2, Calendar, Users, Wallet, FileText, Settings, Bell, Receipt, Wrench, TrendingUp, Search, Activity, LandPlot, Hotel, BadgeDollarSign, FileCheck2, ShieldCheck } from 'lucide-react';

export const ownerNav = [
  {
    label: 'Dashboard',
    section: 'Overview',
    to: '/owner',
    icon: <LayoutDashboard className="w-5 h-5" />,
  },
  {
    label: 'Properties',
    section: 'Portfolio',
    to: '/owner/properties',
    icon: <Building2 className="w-5 h-5" />,
  },
  {
    label: 'Portfolio & Assets',
    section: 'Portfolio',
    to: '/owner/portfolio',
    icon: <LandPlot className="w-5 h-5" />,
  },
  {
    label: 'Short-Stay Operations',
    section: 'Operations',
    to: '/owner/short-stay',
    icon: <Hotel className="w-5 h-5" />,
  },
  {
    label: 'Sales & Disposals',
    section: 'Operations',
    to: '/owner/sales',
    icon: <BadgeDollarSign className="w-5 h-5" />,
  },
  {
    label: 'Reservations',
    section: 'Operations',
    to: '/owner/reservations',
    icon: <Calendar className="w-5 h-5" />,
  },
  {
    label: 'Occupants & Clients',
    section: 'Operations',
    to: '/owner/tenants',
    icon: <Users className="w-5 h-5" />,
  },
  {
    label: 'Collections & Payments',
    section: 'Finance',
    to: '/owner/payments',
    icon: <Wallet className="w-5 h-5" />,
  },
  {
    label: 'Expenses',
    section: 'Finance',
    to: '/owner/expenses',
    icon: <Receipt className="w-5 h-5" />,
  },
  {
    label: 'Maintenance',
    section: 'Operations',
    to: '/owner/maintenance',
    icon: <Wrench className="w-5 h-5" />,
  },
  {
    label: 'Tax & KRA',
    section: 'Finance',
    to: '/owner/tax',
    icon: <TrendingUp className="w-5 h-5" />,
  },
  {
    label: 'Messages & Enquiries',
    section: 'Operations',
    to: '/owner/messages',
    icon: <Bell className="w-5 h-5" />,
  },
  {
    label: 'Reports',
    section: 'Insights',
    to: '/owner/reports',
    icon: <FileText className="w-5 h-5" />,
  },
  {
    label: 'Documents',
    section: 'Administration',
    to: '/owner/documents',
    icon: <FileText className="w-5 h-5" />,
  },
  {
    label: 'Settings',
    section: 'Administration',
    to: '/owner/settings',
    icon: <Settings className="w-5 h-5" />,
  },
];

export const tenantNav = [
  {
    label: 'Dashboard',
    section: 'Overview',
    to: '/tenant',
    icon: <LayoutDashboard className="w-5 h-5" />,
  },
  {
    label: 'Explore Assets',
    section: 'My tenancy',
    to: '/properties',
    icon: <Search className="w-5 h-5" />,
  },
  {
    label: 'Reservations',
    section: 'Operations',
    to: '/tenant/reservations',
    icon: <Calendar className="w-5 h-5" />,
  },
  {
    label: 'My Asset',
    section: 'My tenancy',
    to: '/tenant/house',
    icon: <Home className="w-5 h-5" />,
  },
  {
    label: 'Rent & Payments',
    section: 'Finance',
    to: '/tenant/rent',
    icon: <Wallet className="w-5 h-5" />,
  },
  {
    label: 'Lease',
    section: 'My tenancy',
    to: '/tenant/lease',
    icon: <FileText className="w-5 h-5" />,
  },
  {
    label: 'Viewings',
    section: 'Operations',
    to: '/tenant/viewings',
    icon: <Calendar className="w-5 h-5" />,
  },
  {
    label: 'Maintenance',
    section: 'Operations',
    to: '/tenant/maintenance',
    icon: <Wrench className="w-5 h-5" />,
  },
  {
    label: 'Messages',
    section: 'My tenancy',
    to: '/tenant/messages',
    icon: <Bell className="w-5 h-5" />,
  },
  {
    label: 'Documents',
    section: 'Administration',
    to: '/tenant/documents',
    icon: <FileText className="w-5 h-5" />,
  },
  {
    label: 'Settings',
    section: 'Administration',
    to: '/tenant/settings',
    icon: <Settings className="w-5 h-5" />,
  },
];

export const adminNav = [
  {
    label: 'Super Admin Command Center',
    section: 'Super Admin',
    to: '/admin/super-admin',
    superAdminOnly: true,
    icon: <ShieldCheck className="w-5 h-5" />,
  },
  {
    label: 'Dashboard',
    section: 'Overview',
    to: '/admin',
    requiredPermission: ADMIN_PERMISSION.dashboard,
    icon: <LayoutDashboard className="w-5 h-5" />,
  },
  {
    label: 'Properties',
    section: 'Portfolio',
    to: '/admin/properties',
    requiredPermission: ADMIN_PERMISSION.propertiesView,
    icon: <Building2 className="w-5 h-5" />,
  },
  {
    label: 'Portfolio & Assets',
    section: 'Portfolio',
    to: '/admin/portfolio',
    requiredPermission: ADMIN_PERMISSION.propertiesView,
    icon: <LandPlot className="w-5 h-5" />,
  },
  {
    label: 'Users',
    section: 'Administration',
    to: '/admin/users',
    superAdminOnly: true,
    icon: <Users className="w-5 h-5" />,
  },
  {
    label: 'Staff & Access',
    section: 'Administration',
    to: '/admin/staff',
    superAdminOnly: true,
    icon: <ShieldCheck className="w-5 h-5" />,
  },
  {
    label: 'Units & Inventory',
    section: 'Portfolio',
    to: '/admin/units',
    requiredPermission: ADMIN_PERMISSION.unitsView,
    icon: <Building2 className="w-5 h-5" />,
  },
  {
    label: 'Leases & Tenants',
    section: 'Operations',
    to: '/admin/leases',
    requiredPermission: ADMIN_PERMISSION.leasesView,
    icon: <Users className="w-5 h-5" />,
  },
  {
    label: 'Short-Stay Operations',
    section: 'Operations',
    to: '/admin/short-stay',
    requiredPermission: ADMIN_PERMISSION.shortStayView,
    icon: <Hotel className="w-5 h-5" />,
  },
  {
    label: 'Sales & Disposals',
    section: 'Operations',
    to: '/admin/sales',
    requiredPermission: ADMIN_PERMISSION.salesView,
    icon: <BadgeDollarSign className="w-5 h-5" />,
  },
  {
    label: 'Reservations',
    section: 'Operations',
    to: '/admin/reservations',
    requiredPermission: ADMIN_PERMISSION.reservationsView,
    icon: <Calendar className="w-5 h-5" />,
  },
  {
    label: 'Payments',
    section: 'Finance',
    to: '/admin/payments',
    requiredPermission: ADMIN_PERMISSION.paymentsView,
    icon: <Wallet className="w-5 h-5" />,
  },
  {
    label: 'Expenses',
    section: 'Finance',
    to: '/admin/expenses',
    requiredPermission: ADMIN_PERMISSION.expensesView,
    icon: <Receipt className="w-5 h-5" />,
  },
  {
    label: 'Maintenance',
    section: 'Operations',
    to: '/admin/maintenance',
    requiredPermission: ADMIN_PERMISSION.maintenanceView,
    icon: <Wrench className="w-5 h-5" />,
  },
  {
    label: 'Tax & KRA eTIMS',
    section: 'Finance',
    to: '/admin/kra',
    requiredPermission: ADMIN_PERMISSION.taxView,
    icon: <FileCheck2 className="w-5 h-5" />,
  },
  {
    label: 'Documents & Compliance',
    section: 'Administration',
    to: '/admin/documents',
    requiredPermission: ADMIN_PERMISSION.documentsView,
    icon: <FileText className="w-5 h-5" />,
  },
  {
    label: 'Activity & Alerts',
    section: 'Administration',
    to: '/admin/activity',
    requiredPermission: ADMIN_PERMISSION.auditView,
    icon: <Activity className="w-5 h-5" />,
  },
  {
    label: 'Settings',
    section: 'Administration',
    to: '/admin/settings',
    superAdminOnly: true,
    icon: <Settings className="w-5 h-5" />,
  },
];
