CREATE OR REPLACE FUNCTION public.get_admin_financial_command_center(p_period text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_user uuid := auth.uid(); v_start date; v_end date; v_six date; v_expected numeric:=0; v_collected numeric:=0; v_expenses numeric:=0; v_arrears numeric:=0; v_payouts numeric:=0; v_monthly jsonb:='[]'; v_properties jsonb:='[]';
BEGIN
 IF v_user IS NULL OR NOT EXISTS (SELECT 1 FROM profiles WHERE id=v_user AND role='admin') THEN RAISE EXCEPTION 'Administrator access required'; END IF;
 IF p_period !~ '^\d{4}-\d{2}$' THEN RAISE EXCEPTION 'Invalid reporting period'; END IF;
 v_start:=to_date(p_period||'-01','YYYY-MM-DD'); v_end:=(v_start+interval '1 month')::date; v_six:=(v_start-interval '5 months')::date;
 SELECT COALESCE(sum(amount),0) INTO v_expected FROM rent_invoices WHERE period=p_period;
 SELECT COALESCE(sum(amount),0) INTO v_collected FROM payments WHERE payment_type='rent' AND status='successful' AND verified=true AND created_at>=v_start AND created_at<v_end;
 SELECT COALESCE(sum(amount),0) INTO v_expenses FROM expenses WHERE expense_date>=v_start AND expense_date<v_end;
 SELECT COALESCE(sum(GREATEST(balance,0)),0) INTO v_arrears FROM rent_invoices WHERE period=p_period AND due_date<CURRENT_DATE AND balance>0;
 SELECT COALESCE(sum(net_amount),0) INTO v_payouts FROM owner_payouts WHERE period=p_period AND status<>'failed';
 SELECT COALESCE(jsonb_agg(jsonb_build_object('period',to_char(m.month_start,'YYYY-MM'),'expected',COALESCE((SELECT sum(ri.amount) FROM rent_invoices ri WHERE ri.period=to_char(m.month_start,'YYYY-MM')),0),'collected',COALESCE((SELECT sum(p.amount) FROM payments p WHERE p.payment_type='rent' AND p.status='successful' AND p.verified=true AND p.created_at>=m.month_start AND p.created_at<m.month_start+interval '1 month'),0),'expenses',COALESCE((SELECT sum(e.amount) FROM expenses e WHERE e.expense_date>=m.month_start::date AND e.expense_date<(m.month_start+interval '1 month')::date),0),'payouts',COALESCE((SELECT sum(op.net_amount) FROM owner_payouts op WHERE op.period=to_char(m.month_start,'YYYY-MM') AND op.status<>'failed'),0)) ORDER BY m.month_start),'[]') INTO v_monthly FROM generate_series(v_six,v_start,interval '1 month') m(month_start);
 SELECT COALESCE(jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'expected',COALESCE((SELECT sum(ri.amount) FROM rent_invoices ri WHERE ri.property_id=p.id AND ri.period=p_period),0),'collected',COALESCE((SELECT sum(pm.amount) FROM payments pm WHERE pm.property_id=p.id AND pm.payment_type='rent' AND pm.status='successful' AND pm.verified=true AND pm.created_at>=v_start AND pm.created_at<v_end),0),'expenses',COALESCE((SELECT sum(ex.amount) FROM expenses ex WHERE ex.property_id=p.id AND ex.expense_date>=v_start AND ex.expense_date<v_end),0),'units',COALESCE((SELECT count(*) FROM property_units u WHERE u.property_id=p.id),0),'occupied',COALESCE((SELECT count(*) FROM property_units u WHERE u.property_id=p.id AND u.status='occupied'),0),'net',COALESCE((SELECT sum(pm.amount) FROM payments pm WHERE pm.property_id=p.id AND pm.payment_type='rent' AND pm.status='successful' AND pm.verified=true AND pm.created_at>=v_start AND pm.created_at<v_end),0)-COALESCE((SELECT sum(ex.amount) FROM expenses ex WHERE ex.property_id=p.id AND ex.expense_date>=v_start AND ex.expense_date<v_end),0)) ORDER BY p.name),'[]') INTO v_properties FROM properties p;
 RETURN jsonb_build_object('period',p_period,'expected_rent',v_expected,'collected_rent',v_collected,'collection_rate',CASE WHEN v_expected>0 THEN round(v_collected/v_expected*100,1) ELSE 0 END,'arrears',v_arrears,'expenses',v_expenses,'net_operating_income',v_collected-v_expenses,'owner_payouts',v_payouts,'monthly',v_monthly,'properties',v_properties);
END; $$;
REVOKE ALL ON FUNCTION public.get_admin_financial_command_center(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_admin_financial_command_center(text) TO authenticated;
